// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwY15nHPzkPG-T9HHe6vQ_NxW424uvl5Q',
    appId: '1:685784109582:web:a435eda180b6ba94bd625f',
    messagingSenderId: '685784109582',
    projectId: 'time-tracker-dev-4d1cc',
    authDomain: 'time-tracker-dev-4d1cc.firebaseapp.com',
    storageBucket: 'time-tracker-dev-4d1cc.firebasestorage.app',
    measurementId: 'G-R9T1HGW2JW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoYUXQtR-JmSp9f2nMAm-H8duCxnPpunk',
    appId: '1:685784109582:android:34547aff8062d208bd625f',
    messagingSenderId: '685784109582',
    projectId: 'time-tracker-dev-4d1cc',
    storageBucket: 'time-tracker-dev-4d1cc.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbcaRvUXQ576MMwllsyIWxrxWjufKtCy8',
    appId: '1:685784109582:ios:cf71ee23e4fc2af3bd625f',
    messagingSenderId: '685784109582',
    projectId: 'time-tracker-dev-4d1cc',
    storageBucket: 'time-tracker-dev-4d1cc.firebasestorage.app',
    iosClientId: '685784109582-ofkf1n5b5t6o7beon0r8roku8704d6m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbcaRvUXQ576MMwllsyIWxrxWjufKtCy8',
    appId: '1:685784109582:ios:cf71ee23e4fc2af3bd625f',
    messagingSenderId: '685784109582',
    projectId: 'time-tracker-dev-4d1cc',
    storageBucket: 'time-tracker-dev-4d1cc.firebasestorage.app',
    iosClientId: '685784109582-ofkf1n5b5t6o7beon0r8roku8704d6m5.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwY15nHPzkPG-T9HHe6vQ_NxW424uvl5Q',
    appId: '1:685784109582:web:8a060329faf98426bd625f',
    messagingSenderId: '685784109582',
    projectId: 'time-tracker-dev-4d1cc',
    authDomain: 'time-tracker-dev-4d1cc.firebaseapp.com',
    storageBucket: 'time-tracker-dev-4d1cc.firebasestorage.app',
    measurementId: 'G-PNZ69GG8MH',
  );
}
